document: feedback-pipeline-workload
version: 1
data:
  name: Apache Subversion
  description: Apache Subversion version control
  maintainer: sst_cs_stacks

  modules_enable:
  - subversion:1.14

  packages:
  - subversion
  - mod_dav_svn
  - subversion-tools
  - python3-subversion
  - subversion-devel
  
  labels:
  - eln
